name: flutter_app
description: A new Flutter application.

#RUN
#1 flutter pub get
#2 flutter packages pub run build_runner build --delete-conflicting-outputs
#3 flutter pub run flutter_native_splash:create

#ENVIRONMENT
#  Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
#  Framework • revision 7e9793dee1 (5 weeks ago) • 2022-03-02 11:23:12 -0600
#  Engine • revision bd539267b4
#  Tools • Dart 2.16.1 • DevTools 2.9.2

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  provider: ^6.0.2
  flutter_easyloading: ^3.0.3
  json_serializable: ^4.1.4
  json_annotation: ^4.0.0
  shared_preferences: ^2.0.7
  get: 4.6.1
  connectivity: ^3.0.6
  chopper: ^4.0.5
  cached_network_image: ^3.2.0
  dio: ^4.0.4
  firebase_analytics: ^9.1.1
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.7
  flutter_local_notifications: ^9.5.3+1
  pin_code_fields: ^7.3.0
  intl: ^0.17.0
  flutter_svg: ^0.23.0+1
  easy_mask: ^2.0.1
  firebase_auth: ^3.3.8
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  date_format: ^2.0.5
  jiffy: ^5.0.0
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  vibration: ^1.7.4-nullsafety.0
  dotted_border: ^2.0.0
  barcode: ^2.2.0
  barcode_widget: ^2.0.2
  dotted_decoration: ^2.0.0
  platform_device_id: ^1.0.1
  flutter_facebook_auth: ^4.1.1
  google_sign_in: ^5.1.0
  #  connectivity_plus: ^2.3.0
  image_picker: ^0.8.5
  dropdown_button2: ^1.4.0
  image_cropper: ^1.5.1
  flutter_html: ^2.2.1
  carousel_slider: ^4.1.1
  location: ^4.3.0
  permission_handler: ^9.2.0
  firebase_database: ^9.0.14
  url_launcher: ^6.1.2
  flutter_downloader: ^1.7.4
  path_provider: ^2.0.10
  device_info_plus: ^3.2.3
  system_settings: ^2.1.0
  mime: ^1.0.2
  video_player: ^2.4.2
  #  webview_flutter: ^3.0.4
  webview_flutter: '>=2.0.4 <4.0.0'
  sign_in_with_apple: ^4.1.0
  flutter_inappwebview: ^5.4.3+7
  fl_chart: ^0.55.1
  simple_gesture_detector: ^0.2.0
#  table_calendar:
#    path: ./packages/table_calendar

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  chopper_generator: ^4.0.0
  flutter_native_splash: ^2.1.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/images/2.0x/
    - lib/assets/images/3.0x/
  fonts:
    - family: Bold
      fonts:
        - asset: lib/assets/fonts/Roboto-Bold.ttf
    - family: Italic
      fonts:
        - asset: lib/assets/fonts/Roboto-Italic.ttf
    - family: Regular
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf
    - family: ErasDemiITC
      fonts:
        - asset: lib/assets/fonts/ErasDemiITC.ttf
    - family: sitka-small
      fonts:
        - asset: lib/assets/fonts/sitka-small.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

