// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1-kcQciARDyT3vsP8WLGyVZRizvCoR8I',
    appId: '1:214143541166:android:3d0be52859454a0efa323f',
    messagingSenderId: '214143541166',
    projectId: 'retailer-testt',
    databaseURL: 'https://retailer-testt-default-rtdb.firebaseio.com',
    storageBucket: 'retailer-testt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUf2YcvKrYsP6TpH1gfeA-uSDXBHQE3zg',
    appId: '1:214143541166:ios:e3f693ebc7d4ea91fa323f',
    messagingSenderId: '214143541166',
    projectId: 'retailer-testt',
    databaseURL: 'https://retailer-testt-default-rtdb.firebaseio.com',
    storageBucket: 'retailer-testt.appspot.com',
    androidClientId:
        '214143541166-19su538hi09e6va3e79sd4fddtg95pvb.apps.googleusercontent.com',
    iosClientId:
        '214143541166-trlvtnf04vccfv0fjfju3kf49qsnr62m.apps.googleusercontent.com',
    iosBundleId: 'com.franceskinj.retailer.customer',
  );
}
